services:
  app:
    container_name: solidtime-app
    image: solidtime/solidtime:latest
    user: 1000:1000
    healthcheck:
      disable: true
    ports:
      - 8000:8000/tcp # HTTP web UI
    volumes:
      - /mnt/cache/appdata/solidtime/storage:/var/www/html/storage
      - /mnt/cache/appdata/solidtime/logs:/var/www/html/storage/logs
      - /mnt/cache/appdata/solidtime/app:/var/www/html/storage/app
      - /mnt/cache/appdata/solidtime/views:/var/www/html/storage/framework/views
      - /mnt/cache/appdata/solidtime/cache:/var/www/html/storage/framework/cache
    env_file:
      - .env
    environment:
      CONTAINER_MODE: http
      AUTO_DB_MIGRATE: "true"

  scheduler:
    container_name: solidtime-scheduler
    image: solidtime/solidtime:latest
    user: 1000:1000
    healthcheck:
      disable: true
    volumes:
      - /mnt/cache/appdata/solidtime/storage:/var/www/html/storage
      - /mnt/cache/appdata/solidtime/logs:/var/www/html/storage/logs
      - /mnt/cache/appdata/solidtime/app:/var/www/html/storage/app
      - /mnt/cache/appdata/solidtime/views:/var/www/html/storage/framework/views
      - /mnt/cache/appdata/solidtime/cache:/var/www/html/storage/framework/cache
    env_file:
      - .env
    environment:
      CONTAINER_MODE: scheduler

  queue:
    container_name: solidtime-queue
    image: solidtime/solidtime:latest
    user: 1000:1000
    healthcheck:
      disable: true
    volumes:
      - /mnt/cache/appdata/solidtime/storage:/var/www/html/storage
      - /mnt/cache/appdata/solidtime/logs:/var/www/html/storage/logs
      - /mnt/cache/appdata/solidtime/app:/var/www/html/storage/app
      - /mnt/cache/appdata/solidtime/views:/var/www/html/storage/framework/views
      - /mnt/cache/appdata/solidtime/cache:/var/www/html/storage/framework/cache
    env_file:
      - .env
    environment:
      CONTAINER_MODE: worker
      WORKER_COMMAND: "php /var/www/html/artisan queue:work"

volumes:
  storage:
    driver: local
  logs:
    driver: local
  app-storage:
    driver: local